version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # - MONGO_URI=mongodb://root:1234@database:27017/EStore
      - MONGO_URI=mongodb://database:27017/EStore
    depends_on:
      - database
  
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=EStore
    ports:
      - "27017:27017"

